In [10]:
import pandas as pd

data = {
  "Date" : ["2026-01-01", "2025-02-01", "2024-03-01"]
}

df_date = pd.DataFrame(data)
df_date["Date"] = pd.to_datetime(df_date["Date"])
df_date

        Date
0 2026-01-01
1 2025-02-01
2 2024-03-01

In [11]:
df_date["Date"].dtype

dtype('<M8[us]')

In [12]:
df_date["Year"] = df_date["Date"].dt.year
df_date["Month"] = df_date["Date"].dt.month
df_date["Day"] = df_date["Date"].dt.day

df_date

        Date  Year  Month  Day
0 2026-01-01  2026      1    1
1 2025-02-01  2025      2    1
2 2024-03-01  2024      3    1

In [15]:
df_date[df_date["Date"] > "2025-01-31"]

        Date  Year  Month  Day
0 2026-01-01  2026      1    1
1 2025-02-01  2025      2    1

In [28]:
dates = pd.date_range(start="2023-01-01", periods=5, freq="B")
dates

DatetimeIndex(['2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
               '2023-01-06'],
              dtype='datetime64[us]', freq='B')

In [29]:
df_date.set_index("Date", inplace=True)
df_date

            Year  Month  Day
Date
2026-01-01  2026      1    1
2025-02-01  2025      2    1
2024-03-01  2024      3    1

In [31]:
df_date.sort_index()

            Year  Month  Day
Date
2024-03-01  2024      3    1
2025-02-01  2025      2    1
2026-01-01  2026      1    1