In [2]:
import pandas as pd

data = {
  "Name": ["A","A","B","B"],
  "Subject": ["Math", "Science", "Math", "Science"],
  "Marks": [90,80,85,88]
}

df = pd.DataFrame(data)
df

  Name  Subject  Marks
0    A     Math     90
1    A  Science     80
2    B     Math     85
3    B  Science     88

### Pivot

In [3]:
pivot_df = df.pivot(index="Name", columns="Subject", values="Marks")
pivot_df

Subject  Math  Science
Name
A          90       80
B          85       88

### Melt

In [8]:
df_melt = pd.melt(pivot_df.reset_index(), id_vars=["Name"], value_vars=["Math", "Science"])
df_melt

  Name  Subject  value
0    A     Math     90
1    B     Math     85
2    A  Science     80
3    B  Science     88

### Stack

In [13]:
df_stack = pivot_df.stack()
df_stack

Name  Subject
A     Math       90
      Science    80
B     Math       85
      Science    88
dtype: int64

### Unstack

In [14]:
df_unstack = df_stack.unstack()
df_unstack

Subject  Math  Science
Name
A          90       80
B          85       88